# This is a basic workflow to help you get started with Actions

name: minutesone

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # cron: '0 0-23/12 * * *'
  schedule:
    - cron: '30 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Check PowerShell version
        run: Write-Output $PSVersionTable
        
      - name: Install CoreePower.Lib
        run: Install-Module CoreePower.Lib -Scope CurrentUser -Force
   
      - name: Run Initialize-CorePowerLatest
        run: Initialize-CorePowerLatest
        
      - name: Sample secret step
        run: echo "The secret is ${{ secrets.YOUR_SECRET }}"
        
      - name: Secret to file
        run: Write-Output "${{ secrets.YOUR_SECRET }}" | Out-File fool.txt -NoClobber
        
      - name: Secret display
        run: Write-Output "$(Get-Content -Path fool.txt)"
        
      
        
        
